CREATE TABLE IF NOT EXISTS USERS (
    USER_ID bigint NOT NULL AUTO_INCREMENT,
    EMAIL varchar(100) NOT NULL UNIQUE,
    USERNAME varchar(100) NOT NULL,
    PASSWORD varchar(100) NOT NULL,
    PRIMARY KEY (USER_ID)
);